Modify asyncio interface based on PR #76
ncclient/ncclient pull request #426
Opened 2020-09-02 04:15 UTC by fredgan

Hi @einarnn ,
This PR implements asyncio interface based on PR #76, please review it. :-)

The following is my solution:
1. the connect interface is normalized so that a sync_connect or async_connect can be selected based on async_mode in `manager.py`
2. move the class Manager from `manager.py` to `sync_manager.py`
3. add an `async_manager.py` that contains class AsyncioManager and asyncio_connect function
4. add an example to show how to use async_mode
5. add a testcase to `test_manager.py`, and skip asyncio in python2

2020-09-19 20:11 UTC, einarnn requested changes
In general I'm ok with the strategy here as a way of minimally changing the synchronous code we have today. What I would ideally liked to have had is something where the comms code is rewritten to be "fully asyncio", but leveraging the existing payload & message parsing, but I get that that is a big chunk of work!

This is an acceptable compromise, but taking into account the changes I have requested.

2020-09-19 20:11 UTC, einarnn commented on ncclient/manager.py
> +    return Manager(session, device_handler, manager_params=manager_params)
This needs to not be changed.

2020-09-19 20:11 UTC, einarnn commented on ncclient/manager.py
> +    return Manager(session, device_handler, manager_params=manager_params)
This needs to not be changed.

2020-09-19 20:11 UTC, einarnn commented on ncclient/manager.py
> -class Manager(object):
I don't see the need to create a new `sync_manager.py` file. This makes it really hard to track any diffs in the original `class Manager`. Introducing the new `async_manager.py` is fair enough.

2020-09-19 20:11 UTC, einarnn commented on ncclient/sync_manager.py
> +import logging
Mirroring earlier comment -- let's leave all this code where it was originally.

2020-09-19 20:11 UTC, einarnn commented on ncclient/async_manager.py
> +            manager_params=manager_params,
This needs to reflect not having `manager_params`.

2020-11-04 23:18 UTC, einarnn commented
@fredgan, can you update this PR with respect to the various commits that have been merged?

Cheers,

Einar

2020-11-10 08:53 UTC, fredgan commented
@einarnn Update done.

2025-06-24 17:29 UTC, einarnn commented
Too old.

2025-06-24 17:29 UTC, closed without merging