Bugfix url option is missing for edit-config
ncclient/ncclient pull request #434
Opened 2020-09-16 13:41 UTC by fredgan

Hi, 
This PR adds a `url` option to `edit-config`, as mentioned #431. :-)

2020-09-19 14:42 UTC, einarnn requested changes
Please see review comments.

2020-09-19 14:42 UTC, einarnn commented on ncclient/operations/edit.py
>          if format == 'text':
can you change `if` to `elif`?

2020-09-19 14:42 UTC, einarnn commented on ncclient/operations/edit.py
> +        if format == 'url':
can you change `if` to `elif`?

2020-09-19 14:42 UTC, einarnn commented on ncclient/operations/edit.py
> +            if "://" in config:
You should probably use https://docs.python.org/3/library/urllib.parse.html to check for URL validity.

2020-10-09 07:31 UTC, fredgan commented
@einarnn Hi Einar, They have been modified. Please review it again.

2020-10-09 14:00 UTC, einarnn approved these changes

2020-10-09 14:00 UTC, merged